# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revkeen < Formula
  desc "RevKeen CLI — manage payments, subscriptions & billing from your terminal"
  homepage "https://revkeen.com"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/revkeen/cli/releases/download/v0.2.1/revkeen_darwin_amd64.tar.gz"
      sha256 "8c4c0250c6c6149756da1d5bc25d7f1d2e2dd0bc7df39962bc57374a38942f35"

      define_method(:install) do
        bin.install "revkeen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/revkeen/cli/releases/download/v0.2.1/revkeen_darwin_arm64.tar.gz"
      sha256 "111497d46abb8a5692665874082f8103fcdbadd6d0bfdfd9c85c154f591452c2"

      define_method(:install) do
        bin.install "revkeen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/revkeen/cli/releases/download/v0.2.1/revkeen_linux_amd64.tar.gz"
      sha256 "b2eba30d395d8ffe54b876a65444df64d69de7c123e6529d4020921ef1902688"
      define_method(:install) do
        bin.install "revkeen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/revkeen/cli/releases/download/v0.2.1/revkeen_linux_arm64.tar.gz"
      sha256 "d5c0f0a9827698d9ff399108c3a9988ab2d327c731e28af7a5813320bf7e66d4"
      define_method(:install) do
        bin.install "revkeen"
      end
    end
  end

  test do
    system "#{bin}/revkeen", "--version"
  end
end
